

import { Inter } from "next/font/google";
import "./globals.css";
import { Registry as StyledComponentRegistry } from "@/style/registry";
import Header from "@/components/Header";
import { AuthContextProvider } from "@/context/authContext";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
export default function RootLayout({ children }) {
  return (
    <QueryClientProvider client={queryClient}>
      <AuthContextProvider>
        <html lang="ko">

          <body className={inter.className}>
            <Header />
            <StyledComponentRegistry>{children}</StyledComponentRegistry>

          </body>
        </html>
      </AuthContextProvider>
    </QueryClientProvider>
  );
}
